apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQTZHQk1FNllOTVlPMlpQNUo=
  AWS_SECRET_ACCESS_KEY: V0k5S3M3NkhGc3luZ25FdGpkWTljMFVYTjBid012OVl3dE9maHowKyA=
